/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.enviados;

import RSMaterialComponent.RSTableMetroCustom;
import java.awt.Color;
import modelo.MetodosBD;

/**
 *
 * @author Kevin Benitez
 */
public class tabContenidoEnv extends javax.swing.JPanel
{

    /**
     * Creates new form tabContenido
     */
    public tabContenidoEnv()
    {
        initComponents();
        jScrollPane1.getViewport().setBackground(Color.white);
        listarPaquetes(tblPaquetesEnv);
    }

    public static void listarPaquetes(RSTableMetroCustom tabla)
    {
        MetodosBD.consultaBD(2, tabla);
        //Funciones_aux.getTable(rs, tabla, arr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPaquetesEnv = new RSMaterialComponent.RSTableMetroCustom();
        txtBusqueda = new RSMaterialComponent.RSTextFieldIconOne();
        jCBTipoBusqueda = new RSMaterialComponent.RSComboBox();

        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        tblPaquetesEnv.setForeground(new java.awt.Color(255, 255, 255));
        tblPaquetesEnv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String []
            {
                "Numero de guia", "Nombe del emisor", "Fecha de recepcion", "Nombre del receptor", "Dirección", "Fecha de entrega", "Peso", "Altura", "Ancho", "Profundiidad", "Precio"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblPaquetesEnv.setBackgoundHead(new java.awt.Color(0, 153, 204));
        tblPaquetesEnv.setBackgoundHover(new java.awt.Color(0, 153, 204));
        tblPaquetesEnv.setColorBorderHead(new java.awt.Color(255, 255, 255));
        tblPaquetesEnv.setColorBorderRows(new java.awt.Color(255, 255, 255));
        tblPaquetesEnv.setColorPrimaryText(new java.awt.Color(0, 153, 204));
        tblPaquetesEnv.setColorSecundaryText(new java.awt.Color(0, 153, 204));
        tblPaquetesEnv.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        tblPaquetesEnv.setFontHead(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        tblPaquetesEnv.setFontRowHover(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        tblPaquetesEnv.setFontRowSelect(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        tblPaquetesEnv.setGridColor(new java.awt.Color(255, 255, 255));
        tblPaquetesEnv.setSelectionBackground(new java.awt.Color(0, 153, 204));
        jScrollPane1.setViewportView(tblPaquetesEnv);

        txtBusqueda.setForeground(new java.awt.Color(103, 177, 202));
        txtBusqueda.setBorderColor(new java.awt.Color(103, 177, 202));
        txtBusqueda.setColorIcon(new java.awt.Color(103, 177, 202));
        txtBusqueda.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtBusqueda.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        txtBusqueda.setPhColor(new java.awt.Color(103, 177, 202));
        txtBusqueda.setPlaceholder("Busqueda");
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                txtBusquedaKeyReleased(evt);
            }
        });

        jCBTipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Numero de guía", "Nombre del emisor", "Nombre del receptor", "Dirección", "Fecha de recibido", "Fecha de entrega" }));
        jCBTipoBusqueda.setColorArrow(new java.awt.Color(103, 177, 202));
        jCBTipoBusqueda.setColorBorde(new java.awt.Color(103, 177, 202));
        jCBTipoBusqueda.setColorFondo(new java.awt.Color(103, 177, 202));
        jCBTipoBusqueda.setColorSeleccion(new java.awt.Color(103, 177, 202));
        jCBTipoBusqueda.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jCBTipoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 672, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCBTipoBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtBusquedaKeyReleased
    {//GEN-HEADEREND:event_txtBusquedaKeyReleased
        MetodosBD.busqBD(txtBusqueda.getText(), jCBTipoBusqueda.getSelectedIndex()+1, 2,tblPaquetesEnv);
    }//GEN-LAST:event_txtBusquedaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSComboBox jCBTipoBusqueda;
    private javax.swing.JScrollPane jScrollPane1;
    public static RSMaterialComponent.RSTableMetroCustom tblPaquetesEnv;
    private RSMaterialComponent.RSTextFieldIconOne txtBusqueda;
    // End of variables declaration//GEN-END:variables

}
