/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paquetes;

import configuracion.Funciones_aux;
import configuracion.Paqs;
import java.awt.Color;
import java.awt.Shape;
import java.awt.Window;
import java.awt.geom.RoundRectangle2D;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import modelo.MetodosBD;
import rojeru_san.complementos.RSUtilities;
import vista.confirmaciones.ConfirmaAcc;

/**
 *
 * @author Kevin Benitez
 */
public class ModificacionesReceptor extends javax.swing.JDialog
{

    Paqs auxObj;
    private Window vtn;
    public static int confirmacion = -1;

    /**
     * Creates new form Altas
     *
     * @param num_guia
     * @param peso
     * @param altura
     * @param ancho
     * @param profundidad
     * @param precio
     */
    public ModificacionesReceptor(Paqs obj)
    {
        initComponents();
        setModal(true);
        RSUtilities.setOpaqueWindow(this, false);
        RSUtilities.setOpacityComponent(this.jPFondo, 150);
        setLocationRelativeTo(null);
        vtn = this;
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        vtn.setShape(forma);

        //Se falsean los label de error para hacerlos invisibles
        vLabelErrModNombreRecpt.setForeground(Color.WHITE);
        vLabelErrModApePRecpt.setForeground(Color.WHITE);
        vLabelErrModApeMRecpt.setForeground(Color.WHITE);
        vLabelErrModCalle.setForeground(Color.WHITE);
        vLabelErrModLocalidad.setForeground(Color.WHITE);
        vLabelErrModCiudad.setForeground(Color.WHITE);
        vLabelErrModCP.setForeground(Color.WHITE);

        //Se coloca la informacion de la dirección del paquete
        rSTF_Calle.setText(obj.getCalle());
        rSTF_Localidad.setText(obj.getLocalidad());
        rSTF_Ciudad.setText(obj.getCiudad());
        rSTF_CP.setText(String.valueOf(obj.getCp()));

        //Colocamos la informacion del emisor del paquete
        rSTF_Nombre_Receptor.setText(obj.getrNombre());
        rSTF_ApeP_Receptor.setText(obj.getrApP());
        rSTF_ApeM_Receptor.setText(obj.getrApM());
        this.auxObj = obj;
    }

    public ModificacionesReceptor()
    {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPFondo = new javax.swing.JPanel();
        jPInteracturador = new javax.swing.JPanel();
        rSPanelPaquete = new RSMaterialComponent.RSPanelBorder();
        jLabel2 = new javax.swing.JLabel();
        rSTF_Nombre_Receptor = new RSMaterialComponent.RSTextFieldOne();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCerrarAltas = new RSMaterialComponent.RSButtonIconOne();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rSTF_Calle = new RSMaterialComponent.RSTextFieldOne();
        jLabel5 = new javax.swing.JLabel();
        rSTF_Localidad = new RSMaterialComponent.RSTextFieldOne();
        vLabelErrModCalle = new javax.swing.JLabel();
        vLabelErrModLocalidad = new javax.swing.JLabel();
        rSTF_Ciudad = new RSMaterialComponent.RSTextFieldOne();
        jLabel13 = new javax.swing.JLabel();
        vLabelErrModCiudad = new javax.swing.JLabel();
        rSTF_CP = new RSMaterialComponent.RSTextFieldOne();
        jLabel15 = new javax.swing.JLabel();
        vLabelErrModCP = new javax.swing.JLabel();
        btnGuardarMod1 = new RSMaterialComponent.RSButtonIconOne();
        rSTF_ApeP_Receptor = new RSMaterialComponent.RSTextFieldOne();
        jLabel3 = new javax.swing.JLabel();
        rSTF_ApeM_Receptor = new RSMaterialComponent.RSTextFieldOne();
        jLabel9 = new javax.swing.JLabel();
        vLabelErrModNombreRecpt = new javax.swing.JLabel();
        vLabelErrModApePRecpt = new javax.swing.JLabel();
        vLabelErrModApeMRecpt = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPFondo.setBackground(new java.awt.Color(0, 0, 0));

        rSPanelPaquete.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelPaquete.setBgBorder(new java.awt.Color(0, 153, 204));
        rSPanelPaquete.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                rSPanelPaqueteMouseMoved(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel2.setText("Nombre ");

        rSTF_Nombre_Receptor.setForeground(new java.awt.Color(0, 0, 0));
        rSTF_Nombre_Receptor.setBorderColor(new java.awt.Color(103, 177, 202));
        rSTF_Nombre_Receptor.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        rSTF_Nombre_Receptor.setPhColor(new java.awt.Color(0, 0, 0));
        rSTF_Nombre_Receptor.setPlaceholder("Ingrese el nombre");
        rSTF_Nombre_Receptor.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                rSTF_Nombre_ReceptorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                rSTF_Nombre_ReceptorKeyTyped(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modificar datos de paquete");

        btnCerrarAltas.setBackground(new java.awt.Color(0, 153, 204));
        btnCerrarAltas.setToolTipText("Cerrar Formulario");
        btnCerrarAltas.setBackgroundHover(new java.awt.Color(103, 177, 202));
        btnCerrarAltas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CANCEL);
        btnCerrarAltas.setRound(15);
        btnCerrarAltas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCerrarAltasActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Datos del receptor");

        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnCerrarAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel4.setText("Calle");

        rSTF_Calle.setForeground(new java.awt.Color(0, 0, 0));
        rSTF_Calle.setBorderColor(new java.awt.Color(103, 177, 202));
        rSTF_Calle.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        rSTF_Calle.setPhColor(new java.awt.Color(0, 0, 0));
        rSTF_Calle.setPlaceholder("Ingrese la calle");
        rSTF_Calle.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                rSTF_CalleFocusLost(evt);
            }
        });
        rSTF_Calle.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                rSTF_CalleKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                rSTF_CalleKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel5.setText("Localidad");

        rSTF_Localidad.setForeground(new java.awt.Color(0, 0, 0));
        rSTF_Localidad.setBorderColor(new java.awt.Color(103, 177, 202));
        rSTF_Localidad.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        rSTF_Localidad.setPhColor(new java.awt.Color(0, 0, 0));
        rSTF_Localidad.setPlaceholder("Ingrese la localidad");
        rSTF_Localidad.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                rSTF_LocalidadFocusLost(evt);
            }
        });
        rSTF_Localidad.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                rSTF_LocalidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                rSTF_LocalidadKeyTyped(evt);
            }
        });

        vLabelErrModCalle.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        vLabelErrModCalle.setForeground(java.awt.Color.red);
        vLabelErrModCalle.setText("Error, verifique calle");

        vLabelErrModLocalidad.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        vLabelErrModLocalidad.setForeground(java.awt.Color.red);
        vLabelErrModLocalidad.setText("Error, verifique localidad");

        rSTF_Ciudad.setForeground(new java.awt.Color(0, 0, 0));
        rSTF_Ciudad.setBorderColor(new java.awt.Color(103, 177, 202));
        rSTF_Ciudad.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        rSTF_Ciudad.setPhColor(new java.awt.Color(0, 0, 0));
        rSTF_Ciudad.setPlaceholder("Ingrese la ciudad");
        rSTF_Ciudad.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                rSTF_CiudadFocusLost(evt);
            }
        });
        rSTF_Ciudad.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                rSTF_CiudadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                rSTF_CiudadKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel13.setText("Ciudad");

        vLabelErrModCiudad.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        vLabelErrModCiudad.setForeground(java.awt.Color.red);
        vLabelErrModCiudad.setText("Error, verifique ciudad");

        rSTF_CP.setForeground(new java.awt.Color(0, 0, 0));
        rSTF_CP.setBorderColor(new java.awt.Color(103, 177, 202));
        rSTF_CP.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        rSTF_CP.setPhColor(new java.awt.Color(0, 0, 0));
        rSTF_CP.setPlaceholder("Ingrese el codigo postal");
        rSTF_CP.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                rSTF_CPFocusLost(evt);
            }
        });
        rSTF_CP.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                rSTF_CPKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                rSTF_CPKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel15.setText("Codigo Postal");

        vLabelErrModCP.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        vLabelErrModCP.setForeground(java.awt.Color.red);
        vLabelErrModCP.setText("Error verifique codigo postal");

        btnGuardarMod1.setBackground(new java.awt.Color(0, 153, 204));
        btnGuardarMod1.setToolTipText("Guardar modificaciones");
        btnGuardarMod1.setBackgroundHover(new java.awt.Color(103, 177, 202));
        btnGuardarMod1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        btnGuardarMod1.setRound(15);
        btnGuardarMod1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnGuardarMod1MouseEntered(evt);
            }
        });
        btnGuardarMod1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGuardarMod1ActionPerformed(evt);
            }
        });

        rSTF_ApeP_Receptor.setForeground(new java.awt.Color(0, 0, 0));
        rSTF_ApeP_Receptor.setBorderColor(new java.awt.Color(103, 177, 202));
        rSTF_ApeP_Receptor.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        rSTF_ApeP_Receptor.setPhColor(new java.awt.Color(0, 0, 0));
        rSTF_ApeP_Receptor.setPlaceholder("Ingrese el apellido paterno");
        rSTF_ApeP_Receptor.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                rSTF_ApeP_ReceptorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                rSTF_ApeP_ReceptorKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel3.setText("Apellido Paterno");

        rSTF_ApeM_Receptor.setForeground(new java.awt.Color(0, 0, 0));
        rSTF_ApeM_Receptor.setBorderColor(new java.awt.Color(103, 177, 202));
        rSTF_ApeM_Receptor.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        rSTF_ApeM_Receptor.setPhColor(new java.awt.Color(0, 0, 0));
        rSTF_ApeM_Receptor.setPlaceholder("Ingrese el apellido materno");
        rSTF_ApeM_Receptor.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                rSTF_ApeM_ReceptorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                rSTF_ApeM_ReceptorKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel9.setText("Apellido Materno");

        vLabelErrModNombreRecpt.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        vLabelErrModNombreRecpt.setForeground(java.awt.Color.red);
        vLabelErrModNombreRecpt.setText("Error, verifique nombre");

        vLabelErrModApePRecpt.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        vLabelErrModApePRecpt.setForeground(java.awt.Color.red);
        vLabelErrModApePRecpt.setText("Error, verifique apellido paterno");

        vLabelErrModApeMRecpt.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        vLabelErrModApeMRecpt.setForeground(java.awt.Color.red);
        vLabelErrModApeMRecpt.setText("Error, verifique apellido materno");

        jLabel10.setBackground(new java.awt.Color(0, 153, 204));
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 204)));

        javax.swing.GroupLayout rSPanelPaqueteLayout = new javax.swing.GroupLayout(rSPanelPaquete);
        rSPanelPaquete.setLayout(rSPanelPaqueteLayout);
        rSPanelPaqueteLayout.setHorizontalGroup(
            rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                        .addComponent(vLabelErrModNombreRecpt, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vLabelErrModApePRecpt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5))
                    .addComponent(vLabelErrModLocalidad)
                    .addComponent(rSTF_Localidad, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(260, 260, 260)
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                        .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vLabelErrModCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rSTF_Calle, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(rSTF_CP, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(vLabelErrModCiudad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rSTF_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(vLabelErrModCP, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(btnGuardarMod1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(rSTF_Nombre_Receptor, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rSTF_ApeP_Receptor, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(14, 14, 14)
                                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rSTF_ApeM_Receptor, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                                        .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(vLabelErrModApeMRecpt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9))
                                        .addGap(0, 41, Short.MAX_VALUE)))))
                        .addContainerGap())))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        rSPanelPaqueteLayout.setVerticalGroup(
            rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rSTF_Nombre_Receptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rSTF_ApeP_Receptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(vLabelErrModNombreRecpt, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(vLabelErrModApePRecpt, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                            .addComponent(rSTF_ApeM_Receptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)))
                    .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                        .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addComponent(vLabelErrModApeMRecpt, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSTF_Calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSTF_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vLabelErrModCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vLabelErrModCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rSTF_Localidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rSTF_CP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vLabelErrModLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vLabelErrModCP, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(btnGuardarMod1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );

        javax.swing.GroupLayout jPInteracturadorLayout = new javax.swing.GroupLayout(jPInteracturador);
        jPInteracturador.setLayout(jPInteracturadorLayout);
        jPInteracturadorLayout.setHorizontalGroup(
            jPInteracturadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInteracturadorLayout.createSequentialGroup()
                .addComponent(rSPanelPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPInteracturadorLayout.setVerticalGroup(
            jPInteracturadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInteracturadorLayout.createSequentialGroup()
                .addComponent(rSPanelPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPFondoLayout = new javax.swing.GroupLayout(jPFondo);
        jPFondo.setLayout(jPFondoLayout);
        jPFondoLayout.setHorizontalGroup(
            jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPInteracturador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPFondoLayout.setVerticalGroup(
            jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPInteracturador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarAltasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCerrarAltasActionPerformed
    {//GEN-HEADEREND:event_btnCerrarAltasActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarAltasActionPerformed

    private void rSTF_CalleKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_rSTF_CalleKeyTyped
    {//GEN-HEADEREND:event_rSTF_CalleKeyTyped
        if (rSTF_Calle.getText().length() >= 20)
        {
            evt.consume();
        }
    }//GEN-LAST:event_rSTF_CalleKeyTyped

    private void rSTF_CalleFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_rSTF_CalleFocusLost
    {//GEN-HEADEREND:event_rSTF_CalleFocusLost

    }//GEN-LAST:event_rSTF_CalleFocusLost

    private void rSTF_LocalidadKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_rSTF_LocalidadKeyTyped
    {//GEN-HEADEREND:event_rSTF_LocalidadKeyTyped
        if (rSTF_Localidad.getText().length() >= 20)
        {
            evt.consume();
        }
    }//GEN-LAST:event_rSTF_LocalidadKeyTyped

    private void rSTF_LocalidadFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_rSTF_LocalidadFocusLost
    {//GEN-HEADEREND:event_rSTF_LocalidadFocusLost

    }//GEN-LAST:event_rSTF_LocalidadFocusLost

    private void rSTF_CiudadKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_rSTF_CiudadKeyTyped
    {//GEN-HEADEREND:event_rSTF_CiudadKeyTyped
        Funciones_aux.mEntradaLetrasNum(evt, 1);
    }//GEN-LAST:event_rSTF_CiudadKeyTyped

    private void rSTF_CiudadFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_rSTF_CiudadFocusLost
    {//GEN-HEADEREND:event_rSTF_CiudadFocusLost

    }//GEN-LAST:event_rSTF_CiudadFocusLost

    private void rSTF_CPKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_rSTF_CPKeyTyped
    {//GEN-HEADEREND:event_rSTF_CPKeyTyped
        if (!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyChar() == '.') || rSTF_CP.getText().length() >= 5)
        {
            evt.consume();
        }
    }//GEN-LAST:event_rSTF_CPKeyTyped

    private void rSTF_CPFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_rSTF_CPFocusLost
    {//GEN-HEADEREND:event_rSTF_CPFocusLost

    }//GEN-LAST:event_rSTF_CPFocusLost

    private void rSPanelPaqueteMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_rSPanelPaqueteMouseMoved
    {//GEN-HEADEREND:event_rSPanelPaqueteMouseMoved

    }//GEN-LAST:event_rSPanelPaqueteMouseMoved

    private void btnGuardarMod1MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnGuardarMod1MouseEntered
    {//GEN-HEADEREND:event_btnGuardarMod1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarMod1MouseEntered

    private void btnGuardarMod1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGuardarMod1ActionPerformed
    {//GEN-HEADEREND:event_btnGuardarMod1ActionPerformed
        auxObj.setrNombre(rSTF_Nombre_Receptor.getText());
        auxObj.setrApP(rSTF_ApeP_Receptor.getText());
        auxObj.setrApM(rSTF_ApeM_Receptor.getText());
        auxObj.setCalle(rSTF_Calle.getText());
        auxObj.setLocalidad(rSTF_Localidad.getText());
        auxObj.setCp(Integer.parseInt(rSTF_CP.getText()));
        auxObj.setCiudad(rSTF_Ciudad.getText());
        MetodosBD.modificacion_Datos_Personales(auxObj, 2);
        MetodosBD.modificacion_Direccion(auxObj);
        ModificacionesPaq.general = auxObj;
        tabContenidoRec.listarPaquetes(tabContenidoRec.tblPaquetesRec);
        dispose();
    }//GEN-LAST:event_btnGuardarMod1ActionPerformed

    private void rSTF_Nombre_ReceptorKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_rSTF_Nombre_ReceptorKeyTyped
    {//GEN-HEADEREND:event_rSTF_Nombre_ReceptorKeyTyped
        Funciones_aux.mEntradaLetrasNum(evt, 1);
    }//GEN-LAST:event_rSTF_Nombre_ReceptorKeyTyped

    private void rSTF_ApeP_ReceptorKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_rSTF_ApeP_ReceptorKeyTyped
    {//GEN-HEADEREND:event_rSTF_ApeP_ReceptorKeyTyped
        Funciones_aux.mEntradaLetrasNum(evt, 1);
    }//GEN-LAST:event_rSTF_ApeP_ReceptorKeyTyped

    private void rSTF_ApeM_ReceptorKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_rSTF_ApeM_ReceptorKeyTyped
    {//GEN-HEADEREND:event_rSTF_ApeM_ReceptorKeyTyped
        Funciones_aux.mEntradaLetrasNum(evt, 1);
    }//GEN-LAST:event_rSTF_ApeM_ReceptorKeyTyped

    private void rSTF_Nombre_ReceptorKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_rSTF_Nombre_ReceptorKeyReleased
    {//GEN-HEADEREND:event_rSTF_Nombre_ReceptorKeyReleased
        boolean resultado = Funciones_aux.mValidarFormu(rSTF_Nombre_Receptor, vLabelErrModNombreRecpt, "required", "Error, verifique nombre");
        btnGuardarMod1.setEnabled(resultado);
    }//GEN-LAST:event_rSTF_Nombre_ReceptorKeyReleased

    private void rSTF_ApeP_ReceptorKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_rSTF_ApeP_ReceptorKeyReleased
    {//GEN-HEADEREND:event_rSTF_ApeP_ReceptorKeyReleased
        boolean resultado = Funciones_aux.mValidarFormu(rSTF_ApeP_Receptor, vLabelErrModApePRecpt, "required", "Error, verifique apellido paterno");
        btnGuardarMod1.setEnabled(resultado);
    }//GEN-LAST:event_rSTF_ApeP_ReceptorKeyReleased

    private void rSTF_ApeM_ReceptorKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_rSTF_ApeM_ReceptorKeyReleased
    {//GEN-HEADEREND:event_rSTF_ApeM_ReceptorKeyReleased
        boolean resultado = Funciones_aux.mValidarFormu(rSTF_ApeM_Receptor, vLabelErrModApeMRecpt, "required", "Error, verifique apellido materno");
        btnGuardarMod1.setEnabled(resultado);
    }//GEN-LAST:event_rSTF_ApeM_ReceptorKeyReleased

    private void rSTF_CiudadKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_rSTF_CiudadKeyReleased
    {//GEN-HEADEREND:event_rSTF_CiudadKeyReleased
        boolean resultado = Funciones_aux.mValidarFormu(rSTF_Ciudad, vLabelErrModCiudad, "required", "Error, verifique ciudad");
        btnGuardarMod1.setEnabled(resultado);
    }//GEN-LAST:event_rSTF_CiudadKeyReleased

    private void rSTF_CPKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_rSTF_CPKeyReleased
    {//GEN-HEADEREND:event_rSTF_CPKeyReleased
        mValidarCP(rSTF_CP, vLabelErrModCP);
    }//GEN-LAST:event_rSTF_CPKeyReleased

    private void rSTF_CalleKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_rSTF_CalleKeyReleased
    {//GEN-HEADEREND:event_rSTF_CalleKeyReleased
        boolean resultado = Funciones_aux.mValidarFormu(rSTF_Calle, vLabelErrModCalle, "required", "Error, verifique calle");
        btnGuardarMod1.setEnabled(resultado);
    }//GEN-LAST:event_rSTF_CalleKeyReleased

    private void rSTF_LocalidadKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_rSTF_LocalidadKeyReleased
    {//GEN-HEADEREND:event_rSTF_LocalidadKeyReleased
        boolean resultado = Funciones_aux.mValidarFormu(rSTF_Localidad, vLabelErrModLocalidad, "required", "Error, verifique localidad");
        btnGuardarMod1.setEnabled(resultado);
    }//GEN-LAST:event_rSTF_LocalidadKeyReleased

    /**
     * Valida una entrada con el formato de un codigo postal (5 digitos)
     *
     * @param vTextField
     * @param vLabelErr
     * @return
     */
    protected boolean mValidarCP(javax.swing.JTextField vTextField, javax.swing.JLabel vLabelErr)
    {
        Pattern pat = Pattern.compile("^[0-9]{5}$");
        Matcher matcher = pat.matcher(vTextField.getText());
        vLabelErr.setForeground((!matcher.find()) ? Color.red : Color.white);
        return matcher.find();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonIconOne btnCerrarAltas;
    private RSMaterialComponent.RSButtonIconOne btnGuardarMod1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPFondo;
    private javax.swing.JPanel jPInteracturador;
    private javax.swing.JPanel jPanel1;
    private RSMaterialComponent.RSPanelBorder rSPanelPaquete;
    private RSMaterialComponent.RSTextFieldOne rSTF_ApeM_Receptor;
    private RSMaterialComponent.RSTextFieldOne rSTF_ApeP_Receptor;
    private RSMaterialComponent.RSTextFieldOne rSTF_CP;
    private RSMaterialComponent.RSTextFieldOne rSTF_Calle;
    private RSMaterialComponent.RSTextFieldOne rSTF_Ciudad;
    private RSMaterialComponent.RSTextFieldOne rSTF_Localidad;
    private RSMaterialComponent.RSTextFieldOne rSTF_Nombre_Receptor;
    private javax.swing.JLabel vLabelErrModApeMRecpt;
    private javax.swing.JLabel vLabelErrModApePRecpt;
    private javax.swing.JLabel vLabelErrModCP;
    private javax.swing.JLabel vLabelErrModCalle;
    private javax.swing.JLabel vLabelErrModCiudad;
    private javax.swing.JLabel vLabelErrModLocalidad;
    private javax.swing.JLabel vLabelErrModNombreRecpt;
    // End of variables declaration//GEN-END:variables
}
