/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paquetes;

import configuracion.Paqs;
import java.awt.Color;
import java.awt.Shape;
import java.awt.Window;
import java.awt.geom.RoundRectangle2D;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import modelo.MetodosBD;
import rojeru_san.complementos.RSUtilities;
import vista.confirmaciones.ConfirmaAcc;

/**
 *
 * @author Kevin Benitez
 */
public class ModificacionesReceptor extends javax.swing.JDialog
{

    private Window vtn;
    public static int confirmacion = -1;

    /**
     * Creates new form Altas
     *
     * @param num_guia
     * @param peso
     * @param altura
     * @param ancho
     * @param profundidad
     * @param precio
     */
    public ModificacionesReceptor(String num_guia, String peso, String altura, String ancho, String profundidad, String precio)
    {
        initComponents();
        setModal(true);
        RSUtilities.setOpaqueWindow(this, false);
        RSUtilities.setOpacityComponent(this.jPFondo, 150);
        setLocationRelativeTo(null);
        vtn = this;
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        vtn.setShape(forma);
       // rSTFNumeroGuia.setText(num_guia);
       // vTextFileModPeso.setText(peso);
       // vTextFileModAltura.setText(altura);
        //vTextFileModAncho.setText(ancho);
        //vTextFileModProfundidad.setText(profundidad);
       
        vLabelErrModPeso.setForeground(Color.WHITE);
        vLabelErrModAltura.setForeground(Color.WHITE);
        vLabelErrModAncho.setForeground(Color.WHITE);
        vLabelErrModProfundidad.setForeground(Color.WHITE);
    }

    public ModificacionesReceptor()
    {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPFondo = new javax.swing.JPanel();
        jPInteracturador = new javax.swing.JPanel();
        rSPanelPaquete = new RSMaterialComponent.RSPanelBorder();
        jLabel2 = new javax.swing.JLabel();
        rSTFNumeroGuia = new RSMaterialComponent.RSTextFieldOne();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCerrarAltas = new RSMaterialComponent.RSButtonIconOne();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCerrarAltas8 = new RSMaterialComponent.RSButtonIconOne();
        jLabel4 = new javax.swing.JLabel();
        vTextFileModPeso = new RSMaterialComponent.RSTextFieldOne();
        jLabel5 = new javax.swing.JLabel();
        vTextFileModAltura = new RSMaterialComponent.RSTextFieldOne();
        vLabelErrModPeso = new javax.swing.JLabel();
        vLabelErrModAltura = new javax.swing.JLabel();
        vTextFileModAncho = new RSMaterialComponent.RSTextFieldOne();
        jLabel13 = new javax.swing.JLabel();
        vLabelErrModAncho = new javax.swing.JLabel();
        vTextFileModProfundidad = new RSMaterialComponent.RSTextFieldOne();
        jLabel15 = new javax.swing.JLabel();
        vLabelErrModProfundidad = new javax.swing.JLabel();
        btnGuardarMod1 = new RSMaterialComponent.RSButtonIconOne();
        rSTFNumeroGuia1 = new RSMaterialComponent.RSTextFieldOne();
        jLabel3 = new javax.swing.JLabel();
        rSTFNumeroGuia2 = new RSMaterialComponent.RSTextFieldOne();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPFondo.setBackground(new java.awt.Color(0, 0, 0));

        rSPanelPaquete.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelPaquete.setBgBorder(new java.awt.Color(0, 153, 204));
        rSPanelPaquete.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                rSPanelPaqueteMouseMoved(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel2.setText("Nombre ");

        rSTFNumeroGuia.setEditable(false);
        rSTFNumeroGuia.setForeground(new java.awt.Color(0, 0, 0));
        rSTFNumeroGuia.setBorderColor(new java.awt.Color(103, 177, 202));
        rSTFNumeroGuia.setFocusable(false);
        rSTFNumeroGuia.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        rSTFNumeroGuia.setPhColor(new java.awt.Color(0, 0, 0));
        rSTFNumeroGuia.setPlaceholder("");

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modificar datos de paquete");

        btnCerrarAltas.setBackground(new java.awt.Color(0, 153, 204));
        btnCerrarAltas.setToolTipText("Cerrar Formulario");
        btnCerrarAltas.setBackgroundHover(new java.awt.Color(103, 177, 202));
        btnCerrarAltas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CANCEL);
        btnCerrarAltas.setRound(15);
        btnCerrarAltas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCerrarAltasActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Datos del receptor");

        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        btnCerrarAltas8.setBackground(new java.awt.Color(0, 153, 204));
        btnCerrarAltas8.setToolTipText("Cerrar Formulario");
        btnCerrarAltas8.setBackgroundHover(new java.awt.Color(103, 177, 202));
        btnCerrarAltas8.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CANCEL);
        btnCerrarAltas8.setRound(15);
        btnCerrarAltas8.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCerrarAltas8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(btnCerrarAltas8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrarAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCerrarAltas8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCerrarAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel4.setText("Calle");

        vTextFileModPeso.setForeground(new java.awt.Color(0, 0, 0));
        vTextFileModPeso.setBorderColor(new java.awt.Color(103, 177, 202));
        vTextFileModPeso.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        vTextFileModPeso.setPhColor(new java.awt.Color(0, 0, 0));
        vTextFileModPeso.setPlaceholder("Ingrese la calle");
        vTextFileModPeso.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                vTextFileModPesoFocusLost(evt);
            }
        });
        vTextFileModPeso.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                vTextFileModPesoKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel5.setText("Localidad");

        vTextFileModAltura.setForeground(new java.awt.Color(0, 0, 0));
        vTextFileModAltura.setBorderColor(new java.awt.Color(103, 177, 202));
        vTextFileModAltura.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        vTextFileModAltura.setPhColor(new java.awt.Color(0, 0, 0));
        vTextFileModAltura.setPlaceholder("Ingrese la localidad");
        vTextFileModAltura.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                vTextFileModAlturaFocusLost(evt);
            }
        });
        vTextFileModAltura.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                vTextFileModAlturaKeyTyped(evt);
            }
        });

        vLabelErrModPeso.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        vLabelErrModPeso.setForeground(java.awt.Color.red);
        vLabelErrModPeso.setText("Error, verifique calle");

        vLabelErrModAltura.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        vLabelErrModAltura.setForeground(java.awt.Color.red);
        vLabelErrModAltura.setText("Error, verifique localidad");

        vTextFileModAncho.setForeground(new java.awt.Color(0, 0, 0));
        vTextFileModAncho.setBorderColor(new java.awt.Color(103, 177, 202));
        vTextFileModAncho.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        vTextFileModAncho.setPhColor(new java.awt.Color(0, 0, 0));
        vTextFileModAncho.setPlaceholder("Ingrese el ancho");
        vTextFileModAncho.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                vTextFileModAnchoFocusLost(evt);
            }
        });
        vTextFileModAncho.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                vTextFileModAnchoKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel13.setText("Ciudad");

        vLabelErrModAncho.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        vLabelErrModAncho.setForeground(java.awt.Color.red);
        vLabelErrModAncho.setText("Error, verifique ciudad");

        vTextFileModProfundidad.setForeground(new java.awt.Color(0, 0, 0));
        vTextFileModProfundidad.setBorderColor(new java.awt.Color(103, 177, 202));
        vTextFileModProfundidad.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        vTextFileModProfundidad.setPhColor(new java.awt.Color(0, 0, 0));
        vTextFileModProfundidad.setPlaceholder("Ingrese la profundidad");
        vTextFileModProfundidad.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                vTextFileModProfundidadFocusLost(evt);
            }
        });
        vTextFileModProfundidad.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                vTextFileModProfundidadKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel15.setText("Codigo Postal");

        vLabelErrModProfundidad.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        vLabelErrModProfundidad.setForeground(java.awt.Color.red);
        vLabelErrModProfundidad.setText("Error verifique codigo postal");

        btnGuardarMod1.setBackground(new java.awt.Color(0, 153, 204));
        btnGuardarMod1.setToolTipText("Guardar modificaciones");
        btnGuardarMod1.setBackgroundHover(new java.awt.Color(103, 177, 202));
        btnGuardarMod1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        btnGuardarMod1.setRound(15);
        btnGuardarMod1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnGuardarMod1MouseEntered(evt);
            }
        });
        btnGuardarMod1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGuardarMod1ActionPerformed(evt);
            }
        });

        rSTFNumeroGuia1.setEditable(false);
        rSTFNumeroGuia1.setForeground(new java.awt.Color(0, 0, 0));
        rSTFNumeroGuia1.setBorderColor(new java.awt.Color(103, 177, 202));
        rSTFNumeroGuia1.setFocusable(false);
        rSTFNumeroGuia1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        rSTFNumeroGuia1.setPhColor(new java.awt.Color(0, 0, 0));
        rSTFNumeroGuia1.setPlaceholder("");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel3.setText("Apellido Paterno");

        rSTFNumeroGuia2.setEditable(false);
        rSTFNumeroGuia2.setForeground(new java.awt.Color(0, 0, 0));
        rSTFNumeroGuia2.setBorderColor(new java.awt.Color(103, 177, 202));
        rSTFNumeroGuia2.setFocusable(false);
        rSTFNumeroGuia2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        rSTFNumeroGuia2.setPhColor(new java.awt.Color(0, 0, 0));
        rSTFNumeroGuia2.setPlaceholder("");

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel9.setText("Apellido Materno");

        javax.swing.GroupLayout rSPanelPaqueteLayout = new javax.swing.GroupLayout(rSPanelPaquete);
        rSPanelPaquete.setLayout(rSPanelPaqueteLayout);
        rSPanelPaqueteLayout.setHorizontalGroup(
            rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(rSTFNumeroGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(rSTFNumeroGuia1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(rSTFNumeroGuia2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vTextFileModPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(vLabelErrModPeso))
                                .addGap(18, 18, 18)
                                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(vTextFileModAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(vLabelErrModAltura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                                        .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(vTextFileModAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vLabelErrModAncho))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(vTextFileModProfundidad, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vLabelErrModProfundidad))))))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelPaqueteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarMod1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        rSPanelPaqueteLayout.setVerticalGroup(
            rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(rSTFNumeroGuia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(rSTFNumeroGuia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(rSTFNumeroGuia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vTextFileModPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vTextFileModAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(vTextFileModAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vTextFileModProfundidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vLabelErrModPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vLabelErrModAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(vLabelErrModAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vLabelErrModProfundidad, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnGuardarMod1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPInteracturadorLayout = new javax.swing.GroupLayout(jPInteracturador);
        jPInteracturador.setLayout(jPInteracturadorLayout);
        jPInteracturadorLayout.setHorizontalGroup(
            jPInteracturadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPInteracturadorLayout.setVerticalGroup(
            jPInteracturadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelPaquete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPFondoLayout = new javax.swing.GroupLayout(jPFondo);
        jPFondo.setLayout(jPFondoLayout);
        jPFondoLayout.setHorizontalGroup(
            jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPInteracturador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPFondoLayout.setVerticalGroup(
            jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPInteracturador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarAltasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCerrarAltasActionPerformed
    {//GEN-HEADEREND:event_btnCerrarAltasActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarAltasActionPerformed

    private void btnCerrarAltas8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCerrarAltas8ActionPerformed
    {//GEN-HEADEREND:event_btnCerrarAltas8ActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarAltas8ActionPerformed

    private void vTextFileModPesoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_vTextFileModPesoKeyTyped
    {//GEN-HEADEREND:event_vTextFileModPesoKeyTyped
        if (!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyChar() == '.'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_vTextFileModPesoKeyTyped

    private void vTextFileModPesoFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_vTextFileModPesoFocusLost
    {//GEN-HEADEREND:event_vTextFileModPesoFocusLost
        mValidarNumerosDouble(vTextFileModPeso, vLabelErrModPeso, 1);

    }//GEN-LAST:event_vTextFileModPesoFocusLost

    private void vTextFileModAlturaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_vTextFileModAlturaKeyTyped
    {//GEN-HEADEREND:event_vTextFileModAlturaKeyTyped
        if (!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyChar() == '.'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_vTextFileModAlturaKeyTyped

    private void vTextFileModAlturaFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_vTextFileModAlturaFocusLost
    {//GEN-HEADEREND:event_vTextFileModAlturaFocusLost
        mValidarNumerosDouble(vTextFileModAltura, vLabelErrModAltura, 2);

    }//GEN-LAST:event_vTextFileModAlturaFocusLost

    private void vTextFileModAnchoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_vTextFileModAnchoKeyTyped
    {//GEN-HEADEREND:event_vTextFileModAnchoKeyTyped
        if (!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyChar() == '.'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_vTextFileModAnchoKeyTyped

    private void vTextFileModAnchoFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_vTextFileModAnchoFocusLost
    {//GEN-HEADEREND:event_vTextFileModAnchoFocusLost
        mValidarNumerosDouble(vTextFileModAncho, vLabelErrModAncho, 2);

    }//GEN-LAST:event_vTextFileModAnchoFocusLost

    private void vTextFileModProfundidadKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_vTextFileModProfundidadKeyTyped
    {//GEN-HEADEREND:event_vTextFileModProfundidadKeyTyped
        if (!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyChar() == '.'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_vTextFileModProfundidadKeyTyped

    private void vTextFileModProfundidadFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_vTextFileModProfundidadFocusLost
    {//GEN-HEADEREND:event_vTextFileModProfundidadFocusLost
        mValidarNumerosDouble(vTextFileModProfundidad, vLabelErrModProfundidad, 2);

    }//GEN-LAST:event_vTextFileModProfundidadFocusLost

    private void rSPanelPaqueteMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_rSPanelPaqueteMouseMoved
    {//GEN-HEADEREND:event_rSPanelPaqueteMouseMoved
        if (vActivarVerificadorPaneMod)
        {
            mHabilitaBtnModNextMouseEntered();
        }
    }//GEN-LAST:event_rSPanelPaqueteMouseMoved

    private void btnGuardarMod1MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnGuardarMod1MouseEntered
    {//GEN-HEADEREND:event_btnGuardarMod1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarMod1MouseEntered

    private void btnGuardarMod1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGuardarMod1ActionPerformed
    {//GEN-HEADEREND:event_btnGuardarMod1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarMod1ActionPerformed

    private boolean vActivarVerificadorPaneMod = false;

    /**
     * Habilita o deshabilita el boton Next verificando si los labels de error
     * no esten visibles
     */
    protected void mHabilitaBtnModNext()
    {
        
    }

    /**
     * Habilita o deshabilita el boton Next verificando si los labels de error
     * no esten visibles activando el metodo para verificar cada TextFile
     */
    protected void mHabilitaBtnModNextMouseEntered()
    {
        vTextFileModAlturaFocusLost(null);
        vTextFileModAnchoFocusLost(null);
        
        vTextFileModPesoFocusLost(null);
        vTextFileModProfundidadFocusLost(null);

       
    }

    /**
     * Valida el texto obtenido para verifcar si es correcto el dato ingresado:
     * d+.d+ o d+
     *
     * @param vTextField TextFile el cual se va a adquierir los datos
     * @param vLabelErr Label de error el que se va a mostrar
     * @param vTipo campo que se esta validando (Peso, Altura, Profundidad,
     * etc.)
     */
    protected void mValidarNumerosDouble(javax.swing.JTextField vTextField, javax.swing.JLabel vLabelErr, int vTipo)
    {
        boolean vExistPunto = false;
        boolean vExceso = false;

        for (int i = 0; i < vTextField.getText().length(); i++)
        {
            if (vTextField.getText().charAt(i) == '.')
            {
                vExistPunto = true;
                break;
            }
        }
        Pattern vPartern;
        Pattern vParternValida;
        if (vExistPunto)
        {
            vPartern = Pattern.compile("^[0-9]+\\.[0-9]+$");
            vParternValida = Pattern.compile("^[0]+\\.[0]+$");
        } else
        {
            vPartern = Pattern.compile("^[0-9]+$");
            vParternValida = Pattern.compile("^[0]+$");
        }
        Matcher vMatcher = vPartern.matcher(vTextField.getText());
        Matcher vMatcherValida = vParternValida.matcher(vTextField.getText());
        if (vMatcher.matches())
        {
            if (!vMatcherValida.matches())
            {
                if (vTipo > 0)
                {
                    switch (vTipo)
                    {
                        case 1:
                            if (Double.parseDouble(vTextField.getText()) > 22)
                            {
                                vLabelErr.setVisible(true);
                                vLabelErr.setText("Exceso de peso");
                            } else
                            {
                                vLabelErr.setVisible(false);
                                mHabilitaBtnModNext();
                            }
                            break;
                        case 2:
                            if (Double.parseDouble(vTextField.getText()) > 100)
                            {
                                vLabelErr.setVisible(true);
                                vLabelErr.setText("Exceso de dimensiones");
                            } else
                            {
                                vLabelErr.setText("Error, verifique altura");
                                vLabelErr.setVisible(false);
                                mHabilitaBtnModNext();
                            }
                            break;
                    }
                }
                if (vExceso == false)
                {

                }

            } else
            {
                vLabelErrModPeso.setText("Error, verifique el peso");
                vLabelErrModAltura.setText("Error, verifique altura");
                vLabelErrModAncho.setText("Error, verifique ancho");
                vLabelErrModProfundidad.setText("Error, verifique profundidad");
                vLabelErr.setVisible(true);
            }
        } else
        {
            vLabelErrModPeso.setText("Error, verifique el peso");
            vLabelErrModAltura.setText("Error, verifique altura");
            vLabelErrModAncho.setText("Error, verifique ancho");
            vLabelErrModProfundidad.setText("Error, verifique profundidad");
            
            vLabelErr.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonIconOne btnCerrarAltas;
    private RSMaterialComponent.RSButtonIconOne btnCerrarAltas8;
    private RSMaterialComponent.RSButtonIconOne btnGuardarMod1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPFondo;
    private javax.swing.JPanel jPInteracturador;
    private javax.swing.JPanel jPanel1;
    private RSMaterialComponent.RSPanelBorder rSPanelPaquete;
    private RSMaterialComponent.RSTextFieldOne rSTFNumeroGuia;
    private RSMaterialComponent.RSTextFieldOne rSTFNumeroGuia1;
    private RSMaterialComponent.RSTextFieldOne rSTFNumeroGuia2;
    private javax.swing.JLabel vLabelErrModAltura;
    private javax.swing.JLabel vLabelErrModAncho;
    private javax.swing.JLabel vLabelErrModPeso;
    private javax.swing.JLabel vLabelErrModProfundidad;
    private RSMaterialComponent.RSTextFieldOne vTextFileModAltura;
    private RSMaterialComponent.RSTextFieldOne vTextFileModAncho;
    private RSMaterialComponent.RSTextFieldOne vTextFileModPeso;
    private RSMaterialComponent.RSTextFieldOne vTextFileModProfundidad;
    // End of variables declaration//GEN-END:variables
}
