/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paquetes;

import RSMaterialComponent.RSTextFieldOne;
import configuracion.Funciones_aux;
import configuracion.Paqs;
import java.awt.Color;
import java.awt.Shape;
import java.awt.Window;
import java.awt.event.KeyEvent;
import java.awt.geom.RoundRectangle2D;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JLabel;
import modelo.MetodosBD;
import rojeru_san.complementos.RSUtilities;
import vista.confirmaciones.ConfirmaAcc;

/**
 *
 * @author Kevin Benitez
 */
public class ModificacionesEmisor extends javax.swing.JDialog
{
    Paqs auxObj;
    private Window vtn;
    public static int confirmacion = -1;
    
    /**
     * Creates new form Altas
     *
     * @param obj contiene toda la informacion para modificar el emisor,
     * receptor y direccion
     */
    public ModificacionesEmisor(Paqs obj)
    {
        initComponents();
        setModal(true);
        RSUtilities.setOpaqueWindow(this, false);
        RSUtilities.setOpacityComponent(this.jPFondo, 150);
        setLocationRelativeTo(null);
        vtn = this;
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        vtn.setShape(forma);
        //Colocamos la informacion del emisor del paquete
        rSTF_Nombre_Emisor.setText(obj.geteNombre());
        rSTF_ApeP_Emisor.setText(obj.geteApP());
        rSTF_ApeM_Emisor.setText(obj.geteApM());
        vLabelErrModApeP.setVisible(false);
        vLabelErrModApeM.setVisible(false);
        vLabelErrModNombre.setVisible(false);
        this.auxObj = obj;
    }

    public ModificacionesEmisor()
    {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPFondo = new javax.swing.JPanel();
        jPInteracturador = new javax.swing.JPanel();
        rSPanelPaquete = new RSMaterialComponent.RSPanelBorder();
        jLabel2 = new javax.swing.JLabel();
        rSTF_Nombre_Emisor = new RSMaterialComponent.RSTextFieldOne();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCerrarAltas = new RSMaterialComponent.RSButtonIconOne();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rSTF_ApeP_Emisor = new RSMaterialComponent.RSTextFieldOne();
        vLabelErrModApeP = new javax.swing.JLabel();
        rSTF_ApeM_Emisor = new RSMaterialComponent.RSTextFieldOne();
        jLabel17 = new javax.swing.JLabel();
        vLabelErrModApeM = new javax.swing.JLabel();
        btnGuardarMod1 = new RSMaterialComponent.RSButtonIconOne();
        vLabelErrModNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPFondo.setBackground(new java.awt.Color(0, 0, 0));

        rSPanelPaquete.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelPaquete.setBgBorder(new java.awt.Color(0, 153, 204));
        rSPanelPaquete.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                rSPanelPaqueteMouseMoved(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel2.setText("Nombre del emisor");

        rSTF_Nombre_Emisor.setForeground(new java.awt.Color(0, 0, 0));
        rSTF_Nombre_Emisor.setBorderColor(new java.awt.Color(103, 177, 202));
        rSTF_Nombre_Emisor.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        rSTF_Nombre_Emisor.setPhColor(new java.awt.Color(0, 0, 0));
        rSTF_Nombre_Emisor.setPlaceholder("Ingrese nombre");
        rSTF_Nombre_Emisor.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                rSTF_Nombre_EmisorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                rSTF_Nombre_EmisorKeyTyped(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modificar datos de paquete");

        btnCerrarAltas.setBackground(new java.awt.Color(0, 153, 204));
        btnCerrarAltas.setToolTipText("Cerrar Formulario");
        btnCerrarAltas.setBackgroundHover(new java.awt.Color(103, 177, 202));
        btnCerrarAltas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CANCEL);
        btnCerrarAltas.setRound(15);
        btnCerrarAltas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCerrarAltasActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Datos del emisor");

        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnCerrarAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel4.setText("Apellido Paterno");

        rSTF_ApeP_Emisor.setForeground(new java.awt.Color(0, 0, 0));
        rSTF_ApeP_Emisor.setBorderColor(new java.awt.Color(103, 177, 202));
        rSTF_ApeP_Emisor.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        rSTF_ApeP_Emisor.setPhColor(new java.awt.Color(0, 0, 0));
        rSTF_ApeP_Emisor.setPlaceholder("Ingrese el apellido paterno");
        rSTF_ApeP_Emisor.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                rSTF_ApeP_EmisorFocusLost(evt);
            }
        });
        rSTF_ApeP_Emisor.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                rSTF_ApeP_EmisorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                rSTF_ApeP_EmisorKeyTyped(evt);
            }
        });

        vLabelErrModApeP.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        vLabelErrModApeP.setForeground(java.awt.Color.red);
        vLabelErrModApeP.setText("Error, verifique apellido paterno");

        rSTF_ApeM_Emisor.setForeground(new java.awt.Color(0, 0, 0));
        rSTF_ApeM_Emisor.setBorderColor(new java.awt.Color(103, 177, 202));
        rSTF_ApeM_Emisor.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        rSTF_ApeM_Emisor.setPhColor(new java.awt.Color(0, 0, 0));
        rSTF_ApeM_Emisor.setPlaceholder("Ingrese el apellido materno");
        rSTF_ApeM_Emisor.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                rSTF_ApeM_EmisorFocusLost(evt);
            }
        });
        rSTF_ApeM_Emisor.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                rSTF_ApeM_EmisorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                rSTF_ApeM_EmisorKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel17.setText("Apellido Materno");

        vLabelErrModApeM.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        vLabelErrModApeM.setForeground(java.awt.Color.red);
        vLabelErrModApeM.setText("Error, verifique apellido materno");

        btnGuardarMod1.setBackground(new java.awt.Color(0, 153, 204));
        btnGuardarMod1.setToolTipText("Guardar modificaciones");
        btnGuardarMod1.setBackgroundHover(new java.awt.Color(103, 177, 202));
        btnGuardarMod1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        btnGuardarMod1.setRound(15);
        btnGuardarMod1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnGuardarMod1MouseEntered(evt);
            }
        });
        btnGuardarMod1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGuardarMod1ActionPerformed(evt);
            }
        });

        vLabelErrModNombre.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        vLabelErrModNombre.setForeground(java.awt.Color.red);
        vLabelErrModNombre.setText("Error, verifique nombre");

        javax.swing.GroupLayout rSPanelPaqueteLayout = new javax.swing.GroupLayout(rSPanelPaquete);
        rSPanelPaquete.setLayout(rSPanelPaqueteLayout);
        rSPanelPaqueteLayout.setHorizontalGroup(
            rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(vLabelErrModNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSTF_Nombre_Emisor, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel17)
                    .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                        .addComponent(vLabelErrModApeM, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardarMod1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rSTF_ApeP_Emisor, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSTF_ApeM_Emisor, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vLabelErrModApeP))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        rSPanelPaqueteLayout.setVerticalGroup(
            rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(rSTF_Nombre_Emisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vLabelErrModNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(rSTF_ApeP_Emisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(vLabelErrModApeP, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(rSTF_ApeM_Emisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(vLabelErrModApeM, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelPaqueteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarMod1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPInteracturadorLayout = new javax.swing.GroupLayout(jPInteracturador);
        jPInteracturador.setLayout(jPInteracturadorLayout);
        jPInteracturadorLayout.setHorizontalGroup(
            jPInteracturadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPInteracturadorLayout.setVerticalGroup(
            jPInteracturadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelPaquete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPFondoLayout = new javax.swing.GroupLayout(jPFondo);
        jPFondo.setLayout(jPFondoLayout);
        jPFondoLayout.setHorizontalGroup(
            jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPInteracturador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPFondoLayout.setVerticalGroup(
            jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPInteracturador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarAltasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCerrarAltasActionPerformed
    {//GEN-HEADEREND:event_btnCerrarAltasActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarAltasActionPerformed

    private void rSTF_ApeP_EmisorKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_rSTF_ApeP_EmisorKeyTyped
    {//GEN-HEADEREND:event_rSTF_ApeP_EmisorKeyTyped
         Funciones_aux.mEntradaLetrasNum(evt, 1);
    }//GEN-LAST:event_rSTF_ApeP_EmisorKeyTyped

    private void rSTF_ApeP_EmisorFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_rSTF_ApeP_EmisorFocusLost
    {//GEN-HEADEREND:event_rSTF_ApeP_EmisorFocusLost
        
    }//GEN-LAST:event_rSTF_ApeP_EmisorFocusLost

    private void rSTF_ApeM_EmisorKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_rSTF_ApeM_EmisorKeyTyped
    {//GEN-HEADEREND:event_rSTF_ApeM_EmisorKeyTyped
        Funciones_aux.mEntradaLetrasNum(evt, 1);
    }//GEN-LAST:event_rSTF_ApeM_EmisorKeyTyped

    private void rSTF_ApeM_EmisorFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_rSTF_ApeM_EmisorFocusLost
    {//GEN-HEADEREND:event_rSTF_ApeM_EmisorFocusLost
       
    }//GEN-LAST:event_rSTF_ApeM_EmisorFocusLost

    private void rSPanelPaqueteMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_rSPanelPaqueteMouseMoved
    {//GEN-HEADEREND:event_rSPanelPaqueteMouseMoved
        
    }//GEN-LAST:event_rSPanelPaqueteMouseMoved

    private void btnGuardarMod1MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnGuardarMod1MouseEntered
    {//GEN-HEADEREND:event_btnGuardarMod1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarMod1MouseEntered

    private void btnGuardarMod1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGuardarMod1ActionPerformed
    {//GEN-HEADEREND:event_btnGuardarMod1ActionPerformed
        auxObj.seteNombre(rSTF_Nombre_Emisor.getText());
        auxObj.seteApP(rSTF_ApeP_Emisor.getText());
        auxObj.seteApM(rSTF_ApeM_Emisor.getText());
        MetodosBD.modificacion_Datos_Personales(auxObj, 1);
        ModificacionesPaq.general = auxObj;
    }//GEN-LAST:event_btnGuardarMod1ActionPerformed

    private void rSTF_Nombre_EmisorKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_rSTF_Nombre_EmisorKeyTyped
    {//GEN-HEADEREND:event_rSTF_Nombre_EmisorKeyTyped
        Funciones_aux.mEntradaLetrasNum(evt, 1);
    }//GEN-LAST:event_rSTF_Nombre_EmisorKeyTyped

    private void rSTF_Nombre_EmisorKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_rSTF_Nombre_EmisorKeyReleased
    {//GEN-HEADEREND:event_rSTF_Nombre_EmisorKeyReleased
        boolean resultado = Funciones_aux.mValidarFormu(rSTF_Nombre_Emisor, vLabelErrModNombre, "required","Error, verifique nombre");
        btnGuardarMod1.setEnabled(resultado);
    }//GEN-LAST:event_rSTF_Nombre_EmisorKeyReleased

    private void rSTF_ApeP_EmisorKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_rSTF_ApeP_EmisorKeyReleased
    {//GEN-HEADEREND:event_rSTF_ApeP_EmisorKeyReleased
        boolean resultado = Funciones_aux.mValidarFormu(rSTF_ApeP_Emisor, vLabelErrModApeP, "required","Error, verifique apellido paterno");
        btnGuardarMod1.setEnabled(resultado);
    }//GEN-LAST:event_rSTF_ApeP_EmisorKeyReleased

    private void rSTF_ApeM_EmisorKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_rSTF_ApeM_EmisorKeyReleased
    {//GEN-HEADEREND:event_rSTF_ApeM_EmisorKeyReleased
        boolean resultado = Funciones_aux.mValidarFormu(rSTF_ApeM_Emisor, vLabelErrModApeM, "required","Error, verifique apellido materno");
        btnGuardarMod1.setEnabled(resultado);
    }//GEN-LAST:event_rSTF_ApeM_EmisorKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonIconOne btnCerrarAltas;
    private RSMaterialComponent.RSButtonIconOne btnGuardarMod1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPFondo;
    private javax.swing.JPanel jPInteracturador;
    private javax.swing.JPanel jPanel1;
    private RSMaterialComponent.RSPanelBorder rSPanelPaquete;
    private RSMaterialComponent.RSTextFieldOne rSTF_ApeM_Emisor;
    private RSMaterialComponent.RSTextFieldOne rSTF_ApeP_Emisor;
    private RSMaterialComponent.RSTextFieldOne rSTF_Nombre_Emisor;
    private javax.swing.JLabel vLabelErrModApeM;
    private javax.swing.JLabel vLabelErrModApeP;
    private javax.swing.JLabel vLabelErrModNombre;
    // End of variables declaration//GEN-END:variables
}
