/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paquetes;

import configuracion.Paqs;
import java.awt.Shape;
import java.awt.Window;
import java.awt.geom.RoundRectangle2D;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import modelo.MetodosBD;
import rojeru_san.complementos.RSUtilities;
import vista.confirmaciones.ConfirmaAcc;

/**
 *
 * @author Kevin Benitez
 */
public class ModificacionesReceptor extends javax.swing.JDialog
{

    Paqs auxObj;
    private Window vtn;
    public static int confirmacion = -1;

    /**
     * Creates new form Altas
     *
     * @param num_guia
     * @param peso
     * @param altura
     * @param ancho
     * @param profundidad
     * @param precio
     */
    public ModificacionesReceptor(Paqs obj)
    {
        initComponents();
        setModal(true);
        RSUtilities.setOpaqueWindow(this, false);
        RSUtilities.setOpacityComponent(this.jPFondo, 150);
        setLocationRelativeTo(null);
        vtn = this;
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        vtn.setShape(forma);
        
        rSTF_Calle.setText(obj.getCalle());
        rSTF_Localidad.setText(obj.getLocalidad());
        rSTF_Ciudad.setText(obj.getCiudad());
        rSTF_CP.setText(String.valueOf(obj.getCp()));

        vLabelErrModPeso.setVisible(false);
        vLabelErrModAltura.setVisible(false);
        vLabelErrModAncho.setVisible(false);

        vLabelErrModProfundidad.setVisible(false);
        
        //Colocamos la informacion del emisor del paquete
        rSTF_Nombre_Receptor.setText(obj.getrNombre());
        rSTF_ApeP_Receptor.setText(obj.getrApP());
        rSTF_ApeM_Receptor.setText(obj.getrApM());
        vLabelErrModPeso.setVisible(false);
        //vLabelErrModCosto.setVisible(false);
        this.auxObj = obj;
    }

    public ModificacionesReceptor()
    {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPFondo = new javax.swing.JPanel();
        jPInteracturador = new javax.swing.JPanel();
        rSPanelPaquete = new RSMaterialComponent.RSPanelBorder();
        jLabel2 = new javax.swing.JLabel();
        rSTF_Nombre_Receptor = new RSMaterialComponent.RSTextFieldOne();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCerrarAltas = new RSMaterialComponent.RSButtonIconOne();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCerrarAltas8 = new RSMaterialComponent.RSButtonIconOne();
        jLabel4 = new javax.swing.JLabel();
        rSTF_Calle = new RSMaterialComponent.RSTextFieldOne();
        jLabel5 = new javax.swing.JLabel();
        rSTF_Localidad = new RSMaterialComponent.RSTextFieldOne();
        vLabelErrModPeso = new javax.swing.JLabel();
        vLabelErrModAltura = new javax.swing.JLabel();
        rSTF_Ciudad = new RSMaterialComponent.RSTextFieldOne();
        jLabel13 = new javax.swing.JLabel();
        vLabelErrModAncho = new javax.swing.JLabel();
        rSTF_CP = new RSMaterialComponent.RSTextFieldOne();
        jLabel15 = new javax.swing.JLabel();
        vLabelErrModProfundidad = new javax.swing.JLabel();
        btnGuardarMod1 = new RSMaterialComponent.RSButtonIconOne();
        rSTF_ApeP_Receptor = new RSMaterialComponent.RSTextFieldOne();
        jLabel3 = new javax.swing.JLabel();
        rSTF_ApeM_Receptor = new RSMaterialComponent.RSTextFieldOne();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPFondo.setBackground(new java.awt.Color(0, 0, 0));

        rSPanelPaquete.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelPaquete.setBgBorder(new java.awt.Color(0, 153, 204));
        rSPanelPaquete.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                rSPanelPaqueteMouseMoved(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel2.setText("Nombre ");

        rSTF_Nombre_Receptor.setEditable(false);
        rSTF_Nombre_Receptor.setForeground(new java.awt.Color(0, 0, 0));
        rSTF_Nombre_Receptor.setBorderColor(new java.awt.Color(103, 177, 202));
        rSTF_Nombre_Receptor.setFocusable(false);
        rSTF_Nombre_Receptor.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        rSTF_Nombre_Receptor.setPhColor(new java.awt.Color(0, 0, 0));
        rSTF_Nombre_Receptor.setPlaceholder("");

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modificar datos de paquete");

        btnCerrarAltas.setBackground(new java.awt.Color(0, 153, 204));
        btnCerrarAltas.setToolTipText("Cerrar Formulario");
        btnCerrarAltas.setBackgroundHover(new java.awt.Color(103, 177, 202));
        btnCerrarAltas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CANCEL);
        btnCerrarAltas.setRound(15);
        btnCerrarAltas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCerrarAltasActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Datos del receptor");

        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        btnCerrarAltas8.setBackground(new java.awt.Color(0, 153, 204));
        btnCerrarAltas8.setToolTipText("Cerrar Formulario");
        btnCerrarAltas8.setBackgroundHover(new java.awt.Color(103, 177, 202));
        btnCerrarAltas8.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CANCEL);
        btnCerrarAltas8.setRound(15);
        btnCerrarAltas8.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCerrarAltas8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(btnCerrarAltas8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrarAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCerrarAltas8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCerrarAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel4.setText("Calle");

        rSTF_Calle.setForeground(new java.awt.Color(0, 0, 0));
        rSTF_Calle.setBorderColor(new java.awt.Color(103, 177, 202));
        rSTF_Calle.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        rSTF_Calle.setPhColor(new java.awt.Color(0, 0, 0));
        rSTF_Calle.setPlaceholder("Ingrese el peso");
        rSTF_Calle.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                rSTF_CalleFocusLost(evt);
            }
        });
        rSTF_Calle.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                rSTF_CalleKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel5.setText("Localidad");

        rSTF_Localidad.setForeground(new java.awt.Color(0, 0, 0));
        rSTF_Localidad.setBorderColor(new java.awt.Color(103, 177, 202));
        rSTF_Localidad.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        rSTF_Localidad.setPhColor(new java.awt.Color(0, 0, 0));
        rSTF_Localidad.setPlaceholder("Ingrese la altura");
        rSTF_Localidad.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                rSTF_LocalidadFocusLost(evt);
            }
        });
        rSTF_Localidad.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                rSTF_LocalidadKeyTyped(evt);
            }
        });

        vLabelErrModPeso.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        vLabelErrModPeso.setForeground(java.awt.Color.red);
        vLabelErrModPeso.setText("Error, verifique calle");

        vLabelErrModAltura.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        vLabelErrModAltura.setForeground(java.awt.Color.red);
        vLabelErrModAltura.setText("Error, verifique localidad");

        rSTF_Ciudad.setForeground(new java.awt.Color(0, 0, 0));
        rSTF_Ciudad.setBorderColor(new java.awt.Color(103, 177, 202));
        rSTF_Ciudad.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        rSTF_Ciudad.setPhColor(new java.awt.Color(0, 0, 0));
        rSTF_Ciudad.setPlaceholder("Ingrese el ancho");
        rSTF_Ciudad.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                rSTF_CiudadFocusLost(evt);
            }
        });
        rSTF_Ciudad.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                rSTF_CiudadKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel13.setText("Ciudad");

        vLabelErrModAncho.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        vLabelErrModAncho.setForeground(java.awt.Color.red);
        vLabelErrModAncho.setText("Error, verifique ciudad");

        rSTF_CP.setForeground(new java.awt.Color(0, 0, 0));
        rSTF_CP.setBorderColor(new java.awt.Color(103, 177, 202));
        rSTF_CP.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        rSTF_CP.setPhColor(new java.awt.Color(0, 0, 0));
        rSTF_CP.setPlaceholder("Ingrese la profundidad");
        rSTF_CP.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                rSTF_CPFocusLost(evt);
            }
        });
        rSTF_CP.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                rSTF_CPKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel15.setText("Codigo Postal");

        vLabelErrModProfundidad.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        vLabelErrModProfundidad.setForeground(java.awt.Color.red);
        vLabelErrModProfundidad.setText("Error verifique codigo postal");

        btnGuardarMod1.setBackground(new java.awt.Color(0, 153, 204));
        btnGuardarMod1.setToolTipText("Guardar modificaciones");
        btnGuardarMod1.setBackgroundHover(new java.awt.Color(103, 177, 202));
        btnGuardarMod1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        btnGuardarMod1.setRound(15);
        btnGuardarMod1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnGuardarMod1MouseEntered(evt);
            }
        });
        btnGuardarMod1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGuardarMod1ActionPerformed(evt);
            }
        });

        rSTF_ApeP_Receptor.setEditable(false);
        rSTF_ApeP_Receptor.setForeground(new java.awt.Color(0, 0, 0));
        rSTF_ApeP_Receptor.setBorderColor(new java.awt.Color(103, 177, 202));
        rSTF_ApeP_Receptor.setFocusable(false);
        rSTF_ApeP_Receptor.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        rSTF_ApeP_Receptor.setPhColor(new java.awt.Color(0, 0, 0));
        rSTF_ApeP_Receptor.setPlaceholder("");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel3.setText("Apellido Paterno");

        rSTF_ApeM_Receptor.setEditable(false);
        rSTF_ApeM_Receptor.setForeground(new java.awt.Color(0, 0, 0));
        rSTF_ApeM_Receptor.setBorderColor(new java.awt.Color(103, 177, 202));
        rSTF_ApeM_Receptor.setFocusable(false);
        rSTF_ApeM_Receptor.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        rSTF_ApeM_Receptor.setPhColor(new java.awt.Color(0, 0, 0));
        rSTF_ApeM_Receptor.setPlaceholder("");

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel9.setText("Apellido Materno");

        javax.swing.GroupLayout rSPanelPaqueteLayout = new javax.swing.GroupLayout(rSPanelPaquete);
        rSPanelPaquete.setLayout(rSPanelPaqueteLayout);
        rSPanelPaqueteLayout.setHorizontalGroup(
            rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rSTF_Calle, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(vLabelErrModPeso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rSTF_Localidad, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(vLabelErrModAltura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rSTF_Ciudad, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(vLabelErrModAncho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rSTF_CP, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(vLabelErrModProfundidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(123, 123, 123)
                                .addComponent(jLabel5)
                                .addGap(86, 86, 86)
                                .addComponent(jLabel13)
                                .addGap(106, 106, 106)
                                .addComponent(jLabel15))
                            .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(rSTF_Nombre_Receptor, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(rSTF_ApeP_Receptor, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(rSTF_ApeM_Receptor, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelPaqueteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarMod1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        rSPanelPaqueteLayout.setVerticalGroup(
            rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(rSTF_Nombre_Receptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(rSTF_ApeP_Receptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rSPanelPaqueteLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(rSTF_ApeM_Receptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSTF_Calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSTF_Localidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSTF_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSTF_CP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(rSPanelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vLabelErrModPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vLabelErrModAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vLabelErrModAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vLabelErrModProfundidad, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGuardarMod1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPInteracturadorLayout = new javax.swing.GroupLayout(jPInteracturador);
        jPInteracturador.setLayout(jPInteracturadorLayout);
        jPInteracturadorLayout.setHorizontalGroup(
            jPInteracturadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPInteracturadorLayout.setVerticalGroup(
            jPInteracturadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelPaquete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPFondoLayout = new javax.swing.GroupLayout(jPFondo);
        jPFondo.setLayout(jPFondoLayout);
        jPFondoLayout.setHorizontalGroup(
            jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPInteracturador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPFondoLayout.setVerticalGroup(
            jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPInteracturador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarAltasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCerrarAltasActionPerformed
    {//GEN-HEADEREND:event_btnCerrarAltasActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarAltasActionPerformed

    private void btnCerrarAltas8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCerrarAltas8ActionPerformed
    {//GEN-HEADEREND:event_btnCerrarAltas8ActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarAltas8ActionPerformed

    private void rSTF_CalleKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_rSTF_CalleKeyTyped
    {//GEN-HEADEREND:event_rSTF_CalleKeyTyped
        if (!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyChar() == '.'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_rSTF_CalleKeyTyped

    private void rSTF_CalleFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_rSTF_CalleFocusLost
    {//GEN-HEADEREND:event_rSTF_CalleFocusLost
        mValidarNumerosDouble(rSTF_Calle, vLabelErrModPeso, 1);

    }//GEN-LAST:event_rSTF_CalleFocusLost

    private void rSTF_LocalidadKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_rSTF_LocalidadKeyTyped
    {//GEN-HEADEREND:event_rSTF_LocalidadKeyTyped
        if (!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyChar() == '.'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_rSTF_LocalidadKeyTyped

    private void rSTF_LocalidadFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_rSTF_LocalidadFocusLost
    {//GEN-HEADEREND:event_rSTF_LocalidadFocusLost
        mValidarNumerosDouble(rSTF_Localidad, vLabelErrModAltura, 2);

    }//GEN-LAST:event_rSTF_LocalidadFocusLost

    private void rSTF_CiudadKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_rSTF_CiudadKeyTyped
    {//GEN-HEADEREND:event_rSTF_CiudadKeyTyped
        if (!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyChar() == '.'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_rSTF_CiudadKeyTyped

    private void rSTF_CiudadFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_rSTF_CiudadFocusLost
    {//GEN-HEADEREND:event_rSTF_CiudadFocusLost
        mValidarNumerosDouble(rSTF_Ciudad, vLabelErrModAncho, 2);

    }//GEN-LAST:event_rSTF_CiudadFocusLost

    private void rSTF_CPKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_rSTF_CPKeyTyped
    {//GEN-HEADEREND:event_rSTF_CPKeyTyped
        if (!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyChar() == '.'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_rSTF_CPKeyTyped

    private void rSTF_CPFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_rSTF_CPFocusLost
    {//GEN-HEADEREND:event_rSTF_CPFocusLost
        mValidarNumerosDouble(rSTF_CP, vLabelErrModProfundidad, 2);

    }//GEN-LAST:event_rSTF_CPFocusLost

    private void rSPanelPaqueteMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_rSPanelPaqueteMouseMoved
    {//GEN-HEADEREND:event_rSPanelPaqueteMouseMoved
        if (vActivarVerificadorPaneMod)
        {
            mHabilitaBtnModNextMouseEntered();
        }
    }//GEN-LAST:event_rSPanelPaqueteMouseMoved

    private void btnGuardarMod1MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnGuardarMod1MouseEntered
    {//GEN-HEADEREND:event_btnGuardarMod1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarMod1MouseEntered

    private void btnGuardarMod1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGuardarMod1ActionPerformed
    {//GEN-HEADEREND:event_btnGuardarMod1ActionPerformed
        auxObj.setrNombre(rSTF_Nombre_Receptor.getText());
        auxObj.setrApP(rSTF_ApeP_Receptor.getText());
        auxObj.setrApM(rSTF_ApeM_Receptor.getText());
        auxObj.setCalle(rSTF_Calle.getText());
        auxObj.setLocalidad(rSTF_Localidad.getText());
        auxObj.setCp(Integer.parseInt(rSTF_CP.getText()));
        auxObj.setCiudad(rSTF_Ciudad.getText());
        MetodosBD.modificacion_Datos_Personales(auxObj, 2);
        MetodosBD.modificacion_Direccion(auxObj);
        ModificacionesPaq.general = auxObj;
    }//GEN-LAST:event_btnGuardarMod1ActionPerformed

    private boolean vActivarVerificadorPaneMod = false;

    /**
     * Habilita o deshabilita el boton Next verificando si los labels de error
     * no esten visibles
     */
    protected void mHabilitaBtnModNext()
    {

    }

    /**
     * Habilita o deshabilita el boton Next verificando si los labels de error
     * no esten visibles activando el metodo para verificar cada TextFile
     */
    protected void mHabilitaBtnModNextMouseEntered()
    {
        /*vTextFileModAlturaFocusLost(null);
        vTextFileModAnchoFocusLost(null);

        vTextFileModPesoFocusLost(null);
        vTextFileModProfundidadFocusLost(null);*/

    }

    /**
     * Valida el texto obtenido para verifcar si es correcto el dato ingresado:
     * d+.d+ o d+
     *
     * @param vTextField TextFile el cual se va a adquierir los datos
     * @param vLabelErr Label de error el que se va a mostrar
     * @param vTipo campo que se esta validando (Peso, Altura, Profundidad,
     * etc.)
     */
    protected void mValidarNumerosDouble(javax.swing.JTextField vTextField, javax.swing.JLabel vLabelErr, int vTipo)
    {
        boolean vExistPunto = false;
        boolean vExceso = false;

        for (int i = 0; i < vTextField.getText().length(); i++)
        {
            if (vTextField.getText().charAt(i) == '.')
            {
                vExistPunto = true;
                break;
            }
        }
        Pattern vPartern;
        Pattern vParternValida;
        if (vExistPunto)
        {
            vPartern = Pattern.compile("^[0-9]+\\.[0-9]+$");
            vParternValida = Pattern.compile("^[0]+\\.[0]+$");
        } else
        {
            vPartern = Pattern.compile("^[0-9]+$");
            vParternValida = Pattern.compile("^[0]+$");
        }
        Matcher vMatcher = vPartern.matcher(vTextField.getText());
        Matcher vMatcherValida = vParternValida.matcher(vTextField.getText());
        if (vMatcher.matches())
        {
            if (!vMatcherValida.matches())
            {
                if (vTipo > 0)
                {
                    switch (vTipo)
                    {
                        case 1:
                            if (Double.parseDouble(vTextField.getText()) > 22)
                            {
                                vLabelErr.setVisible(true);
                                vLabelErr.setText("Exceso de peso");
                            } else
                            {
                                vLabelErr.setVisible(false);
                                mHabilitaBtnModNext();
                            }
                            break;
                        case 2:
                            if (Double.parseDouble(vTextField.getText()) > 100)
                            {
                                vLabelErr.setVisible(true);
                                vLabelErr.setText("Exceso de dimensiones");
                            } else
                            {
                                vLabelErr.setText("Error, verifique altura");
                                vLabelErr.setVisible(false);
                                mHabilitaBtnModNext();
                            }
                            break;
                    }
                }
                if (vExceso == false)
                {

                }

            } else
            {
                vLabelErrModPeso.setText("Error, verifique el peso");
                vLabelErrModAltura.setText("Error, verifique altura");
                vLabelErrModAncho.setText("Error, verifique ancho");
                vLabelErrModProfundidad.setText("Error, verifique profundidad");
                vLabelErr.setVisible(true);
            }
        } else
        {
            vLabelErrModPeso.setText("Error, verifique el peso");
            vLabelErrModAltura.setText("Error, verifique altura");
            vLabelErrModAncho.setText("Error, verifique ancho");
            vLabelErrModProfundidad.setText("Error, verifique profundidad");

            vLabelErr.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonIconOne btnCerrarAltas;
    private RSMaterialComponent.RSButtonIconOne btnCerrarAltas8;
    private RSMaterialComponent.RSButtonIconOne btnGuardarMod1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPFondo;
    private javax.swing.JPanel jPInteracturador;
    private javax.swing.JPanel jPanel1;
    private RSMaterialComponent.RSPanelBorder rSPanelPaquete;
    private RSMaterialComponent.RSTextFieldOne rSTF_ApeM_Receptor;
    private RSMaterialComponent.RSTextFieldOne rSTF_ApeP_Receptor;
    private RSMaterialComponent.RSTextFieldOne rSTF_CP;
    private RSMaterialComponent.RSTextFieldOne rSTF_Calle;
    private RSMaterialComponent.RSTextFieldOne rSTF_Ciudad;
    private RSMaterialComponent.RSTextFieldOne rSTF_Localidad;
    private RSMaterialComponent.RSTextFieldOne rSTF_Nombre_Receptor;
    private javax.swing.JLabel vLabelErrModAltura;
    private javax.swing.JLabel vLabelErrModAncho;
    private javax.swing.JLabel vLabelErrModPeso;
    private javax.swing.JLabel vLabelErrModProfundidad;
    // End of variables declaration//GEN-END:variables
}
