/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paquetes;

/**
 *
 * @author Kevin Benitez
 */
public class Recibidos extends javax.swing.JPanel
{

    /**
     * Creates new form Principal
     */
    public Recibidos()
    {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        rSButtonIcon_new1 = new newscomponents.RSButtonIcon_new();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        rSButtonIcon_new2 = new newscomponents.RSButtonIcon_new();
        rSButtonIcon_new4 = new newscomponents.RSButtonIcon_new();
        pnlSlider = new newscomponents.RSPanelEffect();
        tabContenidoRec1 = new vista.paquetes.tabContenidoRec();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(51, 51, 51)));

        rSButtonIcon_new1.setBackground(new java.awt.Color(103, 177, 202));
        rSButtonIcon_new1.setText("Nuevo paquete");
        rSButtonIcon_new1.setBackgroundHover(new java.awt.Color(0, 153, 153));
        rSButtonIcon_new1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rSButtonIcon_new1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD_CIRCLE);
        rSButtonIcon_new1.setRound(10);
        rSButtonIcon_new1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rSButtonIcon_new1ActionPerformed(evt);
            }
        });

        rSLabelTextIcon1.setForeground(new java.awt.Color(0, 153, 204));
        rSLabelTextIcon1.setText("Paquetes recibidos");
        rSLabelTextIcon1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LOCAL_POST_OFFICE);

        rSButtonIcon_new2.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonIcon_new2.setText("Eliminar paquete");
        rSButtonIcon_new2.setBackgroundHover(new java.awt.Color(0, 153, 153));
        rSButtonIcon_new2.setForegroundIcon(new java.awt.Color(255, 0, 0));
        rSButtonIcon_new2.setForegroundText(new java.awt.Color(0, 0, 0));
        rSButtonIcon_new2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rSButtonIcon_new2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.REMOVE_CIRCLE);
        rSButtonIcon_new2.setRound(10);
        rSButtonIcon_new2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rSButtonIcon_new2ActionPerformed(evt);
            }
        });

        rSButtonIcon_new4.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonIcon_new4.setText("Modificar paquete");
        rSButtonIcon_new4.setBackgroundHover(new java.awt.Color(0, 153, 153));
        rSButtonIcon_new4.setForegroundIcon(new java.awt.Color(0, 153, 204));
        rSButtonIcon_new4.setForegroundText(new java.awt.Color(0, 0, 0));
        rSButtonIcon_new4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rSButtonIcon_new4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        rSButtonIcon_new4.setRound(10);
        rSButtonIcon_new4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rSButtonIcon_new4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSButtonIcon_new1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(rSButtonIcon_new2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(rSButtonIcon_new4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(721, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonIcon_new1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSButtonIcon_new2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonIcon_new4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnlSlider.setBackground(new java.awt.Color(255, 255, 255));
        pnlSlider.add(tabContenidoRec1, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 1523, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(pnlSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 480, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonIcon_new2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rSButtonIcon_new2ActionPerformed
    {//GEN-HEADEREND:event_rSButtonIcon_new2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonIcon_new2ActionPerformed

    private void rSButtonIcon_new4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rSButtonIcon_new4ActionPerformed
    {//GEN-HEADEREND:event_rSButtonIcon_new4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonIcon_new4ActionPerformed

    private void rSButtonIcon_new1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rSButtonIcon_new1ActionPerformed
    {//GEN-HEADEREND:event_rSButtonIcon_new1ActionPerformed
        Altas vtn = new Altas();
        vtn.setModal(true);
        vtn.setVisible(true);
    }//GEN-LAST:event_rSButtonIcon_new1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private newscomponents.RSPanelEffect pnlSlider;
    private newscomponents.RSButtonIcon_new rSButtonIcon_new1;
    private newscomponents.RSButtonIcon_new rSButtonIcon_new2;
    private newscomponents.RSButtonIcon_new rSButtonIcon_new4;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private vista.paquetes.tabContenidoRec tabContenidoRec1;
    // End of variables declaration//GEN-END:variables
}
